### ISSUE TITLE
Edge sets HTTP DNT header even though DNT is disabled in browser settings

### ISSUE THREAD

**Issue by Zarickan** [usefathom/fathom#100]
I installed fathom as per [this](https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom) guide, however when I load the page with the tracking script no data shows up in fathom.

I use nginx, and have set up fathom a long with a reverse proxy as described in the aforementioned guide.

In the fathom logs I get this:
`[23/Jul/2018:19:54:05 +0000] \"GET /collect?id=1C1OQ2rttPIkDV1BoIwF&pid=&p=%2F&h=https%3A%2F%2Fzarickan.com&r=&u=1&nv=1&ns=1 HTTP/1.0\" 0 0"`
Indicating that fathom should be logging something, but doesn't?

**Comment by dannyvankooten** [comment]
Hi @Zarickan,

It looks like the `GET /collect?...` request is being discarded because of [this line here](https://github.com/usefathom/fathom/blob/master/pkg/api/collect.go#L80). We can tell by looking at the last two 0's in that log line, indicating that 0 bytes were sent to the connecting client. 

This is what that `shouldCollect` function looks like.

```go
func shouldCollect(r *http.Request) bool {
	// abort if DNT header is set to "1" (these should have been filtered client-side already)
	if r.Header.Get("DNT") == "1" {
		return false
	}

	// don't track prerendered pages, see https://github.com/usefathom/fathom/issues/13
	if r.Header.Get("X-Moz") == "prefetch" || r.Header.Get("X-Purpose") == "preview" {
		return false
	}

	// abort if this is a bot.
	ua := user_agent.New(r.UserAgent())
	if ua.Bot() {
		return false
	}

	return true
}
```

Can you think of anything that would cause any of these 3 conditionals to return true for visitors of your site, where they should return false? Is this happening on a production website, or just for your own visits? In all browsers?

Thanks in advance!

**Comment by Zarickan** [comment]
@dannyvankooten Hi,

I thought this was an issue with Fathom, however I have now discovered that Edge will add DNT to each request even though I had that option disabled in the settings, great.

![edge_why](https://user-images.githubusercontent.com/3790333/43188282-0a5aa96a-8ff4-11e8-81f2-9f5b80fff11e.PNG)

Sorry.

**Comment by dannyvankooten** [comment]
Hey @Zarickan,

No worries, that's actually very good to know! 

What makes this even weirder is that apparently Edge sets the `navigator.doNotTrack` value correctly on the client-side, but then still sets the request header... 

I'm going to rename this issue and keep it open to see if there's something we should do here.

**Comment by JackEllis** [comment]
Closed. We will be re-visiting DNT, and what it means, in the future.
