### ISSUE TITLE
Referrers per page

### ISSUE THREAD

**Issue by BlueHatbRit** [usefathom/fathom#106]
As a blogger, I tend to get visitors from quite a few different sources. I'm wondering if it would be possible for fathom to use Top Referrers for individual pages? It'd be great to click on a Top Page entry and see where traffic is coming from for it. At the moment I can only make assumptions.

**Comment by pjrvs** [comment]
Fathom is still early on, but we don't plan on adding too many more features to it—for most, lean and simple is working best. That's not to say this couldn't be a feature in the future, but we are going to be very, very picky with what we add—otherwise we'll end up with a GA clone with better privacy :)

As soon as we get a roadmap put together, we'll publish it.
