### ISSUE TITLE
Best database for performance?

### ISSUE THREAD

**Issue by ziburski** [usefathom/fathom#114]
Hi! From what I understand, the default SQLite isn’t great for high-traffic sites. Can anyone recommend if MySQL or Postgres is better for performance? Thanks.

**Comment by dannyvankooten** [comment]
Hey @ziburski,

Just seeing this now, but I wouldn't worry about it too be brutally honest. The application uses a buffering technique which will allow you to collect thousands of pageviews per second even when using SQLite. 

Then there's a second round of buffering which aggregates what's necessary and discards everything else meaning you won't run into any size scaling issues after enough time passes either.

That said, if your system is already running either Postgresql or MySQL then I recommend using that just because it's already running anyway.

Cheers!
