### ISSUE TITLE
Unique/Page View Count

### ISSUE THREAD

**Issue by bradders** [usefathom/fathom#129]
Not sure whether this is a glitch or whether I'm just reading the stats wrong. I've attached a screenshot of my current stats (I know, busy day huh?!)

I'm seeing 0 unique visitors, but 5 page views. Is this because the user who posted the 5 page views is returning? Or should it still register (at least) 1 unique visitor?
<img width="232" alt="screenshot 2018-09-18 10 34 57" src="https://user-images.githubusercontent.com/840983/45705805-6066b180-bb2f-11e8-8246-101b227dd299.png">

**Comment by dannyvankooten** [comment]
Hey @bradders,

This is a downside of the tracking implementation we went for. Since we're not storing or tracking anything personal, we have to rely on storing some stuff on the client-side via a cookie. Unfortunately this also means that this data is stored on a device which may have different timezone settings than the device you're viewing your stats on, which in turn causes this.

An option is for us to let the client-side tracking cookie expire on midnight UTC, but the tradeoff of that would be that it means the user is counted as a "new visitor" if he visits a page at 11:59PM UTC and then another at 00:01AM UTC. In the current implementation, we use the local timezone to only count the visitor as a new visitor at his/her midnight.

Over larger timeframes the stats should still add up correctly and for higher traffic sites it also won't matter as much, but I'll make sure that number always shows as at least 1 if there are pageviews for that day.

**Comment by bradders** [comment]
All good, thanks for the explanation. Happy for the lack of personal data storage to drive some stats to look funky. And, as you say, post launch, my dashboard will look a lot less like a creepy track of one dude's path through the site! 🤣
