### ISSUE TITLE
[Question] Support for React sites

### ISSUE THREAD

**Issue by soupdiver** [usefathom/fathom#197]
I'm setting up a new site which is based on React.
It seems only the `/` path is recognised by fathom.

Are React sites supported in some way? If yes, do I have to do more than adding the snipped to my index site?

**Comment by dannyvankooten** [comment]
Hi @soupdiver,

By default Fathom will try to extract the current request values from `window.location`, so as long as you make sure that the `window.location` is updated correctly (eg through `pushState`) Fathom should be able to extract the correct path.

That said, because the default Fathom snippet only runs on the initial page load you will most likely need to call `fathom('trackPageview')` whenever you want to track a pageview.

Here's a more complete snippet, where you specify which path you would like to increment:

```js
fathom('trackPageview', { path: '/my-page' });
```

**Comment by rllola** [comment]
Hello @dannyvankooten 

I am working with @soupdiver . Thank you for your anwser. I have been using react + react-router. It seems that switching from `HashRouter` to `BrowserRouter` has done the trick. I can confirm that the latest solution update the `window.location` through `pushState`.

Here the documentation which indicate how it works in case others have the same question : https://reacttraining.com/react-router/web/api/BrowserRouter
