### ISSUE TITLE
Idempotent option of adding users 

### ISSUE THREAD

**Issue by LostKobrakai** [usefathom/fathom#201]
I'm using ansible to setup fathom on my nodes and it would be really useful to have a way to either detect if a user is already present or at least not fail when adding a user again. Also some way to update the user would be useful as well.

**Comment by dannyvankooten** [comment]
Hi @LostKobrakai,

Does the Ansible playbook you're using now error out because of the error code returned by the Fathom CLI when trying to add a user that already exists in the connected database? Just trying to see what's needed to get this done.

Do you happen to know how other similar CLI applications usually deal with this, some kind of option like `--skip-if-exists` perhaps?

**Comment by LostKobrakai** [comment]
I've no experience with any other tools similar to that. I'd vote fore your latter example with `update --create-if-not-exists` though or some way to query manually if a user exists. I'm not worried about race conditions for my use case.

**Comment by geerlingguy** [comment]
Ditto this—it would be great if there was either a way to do `--create-if-not-exists`, or use a CLI method to check if the user exists. The former makes it a tiny bit simpler for the end user, but the latter also would be better than the current state (and is probably easier to implement?).

**Comment by geerlingguy** [comment]
Related: https://github.com/usefathom/fathom/issues/110

**Comment by JackEllis** [comment]
@LKaemmerling Haven't marked this as a bug, as I'm not 100% sure, but would definitely appreciate your eyes on this
