### ISSUE TITLE
Track bounce rate

### ISSUE THREAD

**Issue by dannyvankooten** [usefathom/fathom#21]
Bounce = any single pageview that did not result in any additional pageviews/events.

**Comment by matthewmorek** [comment]
I don't think the above is the correct definition of a bounce rate, see explanation on GoSquared help pages: https://www.gosquared.com/customer/en/portal/articles/2171527-engagement-trends-#Bounce%20Rate.

I reckon the same kind of approach would be much more optimistic, since there are a lot of SPAs, single-page microsites, etc, that don't have to navigate away from the page to engage with its content in a passive way.

I have to agree here with GoSquared, and have been measuring my personal site over the last week using both services, and the bounce rate on Fathom suggest there's something wrong with my content (~85% median bounce rate), while GoSquared suggests that the content is performing decently (~60%).

As above, we do not only consume web content actively, but passively as well. What do you folks, think?

**Comment by dannyvankooten** [comment]
Hey @matthewmorek,

So I finally had time to go through the list of open issues for Fathom, and I wholeheartedly agree with you. We're very early stage right now, but improving bounce rate detection is surely on the list.

Once we add event tracking, we'll use that to determine bounce rates too. Any outbound click would be seen as an event, so that would greatly reduce the bounce rate already.

After that, a next step might be to include page scrolling, active reading (window focus for a given duration).

Anyway, I hear you and we're going to work on improving our bounce rate detection mechanism slowly but surely!

**Comment by weavermedia** [comment]
I'll also add 'time on site' as a bounce detector. If a visitor hits the site then clicks around a handful of internal pages and leaves within a few seconds I would still consider that a bounce.
