### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [usefathom/fathom#216]
.

**Comment by tazitus** [comment]
I think I have found the problem with the bars not showing.
The class names for the bar width < 10 in [this line](https://github.com/usefathom/fathom/blob/5e4ce53eb87162b1b401790c4ed527eb00a5300f/assets/src/css/styles.css#L123) are all zero padded. Removing the zeros makes the smaller bars appear as they should.

**Comment by jhabdas** [comment]
@tazitus thanks for the info. it's very loose and difficult to extract meaning from. could you please either close this or update the comments with some _very specific_ actionable suggested changes.

**Comment by tazitus** [comment]
I'm not sure what exactly you find unclear and why you'd want me to close the issue because of that. I pretty much linked to each line and described how to replace it already.

These were really just supposed to be some hints as to the location of the problems, because I haven't worked with Javascript/CSS before or looked at the rest of the code very closely.
I just created a pull request anyway with some of the changes that worked for me. Hopefully that helps a bit.

**Comment by jhabdas** [comment]
Your pull def helps clarify. Time is money 👍
