### ISSUE TITLE
What happened to the DigitalOcean droplet?

### ISSUE THREAD

**Issue by gcsalzburg** [usefathom/fathom#270]
I notice the DigitalOcean droplet has been removed from their marketplace, and the install instructions aren't here either. Is it still possible to run this on DigitalOcean? I tried out the marketplace droplet about three weeks ago from them and it worked very well.

Thanks,

George

**Comment by JackEllis** [comment]
There was a big security issue related to Ubuntu and DO asked us to update it. I've not got round to it due to other priorities (unrelated to Fathom) but you can still install it on DigitalOcean by following the guide here: https://github.com/usefathom/fathom/blob/master/docs/Installation%20instructions.md
