### ISSUE TITLE
Modifying sign-in page for self-hosters...

### ISSUE THREAD

**Issue by weisisheng** [usefathom/fathom#302]
I am running a version in China (on AWS BJ) and the government requires a footer on each "publicly facing" page to have a visible government license # and link to the ministry in charge of internet matters.  This of course, even though I am the only user.  I would appreciate any trailheads on adding this snippet to my version.  Thanks in advance.

**Comment by m1guelpf** [comment]
Could this be (temporarily) solved by adding BASIC auth so that the login page is not "public" anymore? Of course this wouldn't be a permanent solution, but this project is not mantained at the moment (even though, as far as I'm aware, there are plans to do it on the future) so this is probably the easiest way to get you up-and-running.

You could also try to modify and build from source. If you go this way, you'd have to modify [the index.html file](https://github.com/usefathom/fathom/blob/master/assets/src/index.html), which is rendered in every page, then rebuild the binary following [this instructions](https://github.com/usefathom/fathom#development). Good luck! 😄

**Comment by weisisheng** [comment]
Thanks very much.  I will give the .html mod a try (the long route) ;-).

They are real strict about this stuff so a login/password would make send to everyone but them.
