### ISSUE TITLE
Support for multiple domains

### ISSUE THREAD

**Issue by lovethebomb** [usefathom/fathom#36]
Hello!
I recently stumbled upon this project after reading a twitter thread about server logs analytics and other alternatives to Google Analytics...

I know it's only in its early stages, but I was wondering if there was potential support for multiple domains in a hidden roadmap?

I believe that right now the datastore and models are not relying on this type of entity yet, but what are your thoughts on this?

**Comment by dannyvankooten** [comment]
Hey @lovethebomb!

Right now, Fathom is pretty simple meaning that you can install the tracking snippet on multiple domains, point it to the same Fathom instance and it will track data for both domains (which probably isn't all that useful if they are separate websites, but is if you're using subdomains). Is that what you're aiming at?

Or do you mean something like a "site switcher" allowing you to keep track of stats for multiple (unrelated) sites in the same Fathom instance? Because that is definitely something we've been contemplating, but up until now we've decided that it is probably easier to simply spin up a separate instance of Fathom with its own database to properly separate concerns.

**Comment by lovethebomb** [comment]
I was indeed referring to something like a "site switcher" (I got tricked by the neat UI screenshot on usefathom.com!) as having a way of aggregating stats per domain, and not just total page views of, for example, `/` index page of both domains (or sub-domains).

Considering that it's very easy to spin up another instance, this is probably out of scope for now ;)

Thanks for the answer, closing the issue.

**Comment by dannyvankooten** [comment]
@cweagans we hear you, we’re working on this in #50
