### ISSUE TITLE
Table component needs number formatting

### ISSUE THREAD

**Issue by dannyvankooten** [usefathom/fathom#47]
Larger numbers in the table component should be formatted like so: `xx,xxx`.

![image](https://user-images.githubusercontent.com/885856/40847772-8fb7c590-65bd-11e8-890c-3c79129970c0.png)

**Comment by pjrvs** [comment]
My vote: large numbers are formatted to never be more than 4 chrs including decimal place (but not including commas).

examples:

1,865
18.4k
99.8m
525

**Comment by ziburski** [comment]
> My vote: large numbers are formatted to never be more than 4 chrs including decimal place (but not including commas).

Hey @pjrvs, that’s a great idea! Maybe you could even do a cutoff, so that all numbers are in the same format? So if you have one number that’s 18.4k, it’s also 7.21k and 0.18k? Just a thought, since different formats make scanning difficult.

And on the topic of formatting numbers for easy scanning, you could look into [tabular figures](https://www.fonts.com/content/learning/fontology/level-3/numbers/proportional-vs-tabular-figures). Might be tricky to implement if the font doesn’t support it though.

**Comment by pjrvs** [comment]
i agree on format *mostly* but 0.18k is less detail than 1834 and both have 4 characters so why not go with the latter as it's more accurate? i think big numbers need truncating for sure, but smaller numbers can be accurate.

**Comment by ziburski** [comment]
Fair enough. Your example list with four different formats just overwhelmed me a little, since you have to go through every character of every number to figure out which is highest. It likely works out better with real data and sorting though. :)
