### ISSUE TITLE
Zero unique visitors on N number of page loads?

### ISSUE THREAD

**Issue by r-chris** [usefathom/fathom#55]
Hi, I am trying out fathom today and am feeding my fathom instance from 4 different sources. One of them is regularly accessed by a headless browser to perform tests. In the fathom dashboard I can see multiple page loads for that instance, but it specifies 0 unique visitors.

Am I correct to assume that fathom somehow tries to detect potential non-human visitors and doesn't count them or is this just a bug? It would be great if my headless access wasn't considered as a visitor, but shouldn't then the page loads also be at 0 ?

Thanks!

![fathom_zero_unique_visitors](https://user-images.githubusercontent.com/18341652/41238758-01f55a56-6d97-11e8-8a5c-7c258c680ba6.png)

**Comment by dannyvankooten** [comment]
Hi @r-chris,

This is most likely a bug in how Fathom determines the "unique visitor" count. Currently it keeps track of the session on the client-side using a cookie which is valid for 24 hours. Only pageviews without this cookie (or rather; without this page's path in the cookie) will increment the unique visitor count for that page.

Ideally we would reset the session at 00:00 (like Google Analytics currently does) but this introduces other complexities like which timezone to use here, since we store sessions on the client.

> Am I correct to assume that fathom somehow tries to detect potential non-human visitors and doesn't count them or is this just a bug? It would be great if my headless access wasn't considered as a visitor, but shouldn't then the page loads also be at 0 ?

Some user-agent filtering occurs on the server-side to strip out common bots, but we haven't put too much effort into this just yet.

**Comment by dannyvankooten** [comment]
This should be fixed by 70d97b03a15946814f10c4bd53d8d90857ba85cd but once we allow setting a custom timezone we may have to revisit this. But then there's a whole load of things to revisit once we do that, so I'll close this issue for now. :smile:

**Comment by r-chris** [comment]
Thanks - that was very quick.
