### ISSUE TITLE
Config option for URL prefix

### ISSUE THREAD

**Issue by jasewells** [usefathom/fathom#77]
I was hoping to run Fathom on an existing domain (same hostname/port), using a URL prefix to proxy requests to the Fathom backend. I can set up something like this in NGINX:

Request for /fathom/blah proxies to -> http://localhost:9000/blah

Fathom gets the request just fine, but then responds with HTML that has references like `<link href="/assets/css/styles.css" rel="stylesheet">`, which of course doesn’t work since they’re missing my custom /fathom prefix. I would want that example link to instead turn into `<link href="/fathom/assets/css/styles.css" rel="stylesheet">`.

Is there any chance you might add a configuration option that would make Fathom prefix/prepend an arbitrary subdirectory in front of any CSS/JS/media links in its HTML? Not sure if that is even possible with how Fathom serves the asset files?

**Comment by dannyvankooten** [comment]
Hey @jasewells,

I can see how this would simplify managing certs etc. somewhat, so I'm definitely going to look into this. 

It should be possible with how Fathom is serving its asset files, but does require knowledge of the "path to strip off" in order to determine which file is being requested. Nothing a configuration value can't fix however. :smile_cat:

**Comment by zvitez** [comment]
Hey!

Any progress on this? Have the request :)

**Comment by dannyvankooten** [comment]
Hey, sorry for the delay on this. 

After 9589072e42537176471eed3bdc1086fc17e0ccf3, you should now be able to use Fathom from subdirectories. You may have to add a rewrite rule to your server configuration, eg using NGINX:

```
location /fathom/ {
    rewrite ^/fathom(/.*)$ $1 break;
    proxy_pass  http://127.0.0.1:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by zvitez** [comment]
Hey, thanks Danny! I'll try it as soon as it's released

**Comment by JacobEvelyn** [comment]
@dannyvankooten I may be doing something wrong, but when I try the Nginx config above, I get requests to `mysite.com/fathom/...` correctly proxied to the fathom server, but the assets are still requested at `mysite.com/assets/...` instead of `mysite.com/fathom/...`. Looking at the commit you linked, this seems expected, as I believe relative URLs for DOM resources are typically relative to the domain unless there's a [base element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) defined.

In the meantime, I'm using a custom subdomain for my Fathom instance, which isn't ideal but works.

**Comment by xPaw** [comment]
This issue isn't entirely fixed, as the API requests are still executed against the root folder like `/api/session`.
