### ISSUE TITLE
enhancement: page load time

### ISSUE THREAD

**Issue by ckluis** [usefathom/fathom#84]
I really like the direction of Fathom and the idea of analytics with privacy and potential GDPR compliance baked in.  

However that comes with the cost of potentially losing valuable data.   One of the things that I need in analytics is page load time with thresholds (avg, 90, 95%).  I'd understand if that was beyond the scope, but that information really helps with optimization planning.

**Comment by dannyvankooten** [comment]
Hey @ckluis,

Including page load time is definitely something we're willing to consider. We're opening up a public roadmap soon where you can vote for features, so that seems like an appropriate place for this.

I'm closing this issue now as it's not really an issue imo, but I'll update this thread with a link to the roadmap as soon as it is live.

Thank you for chiming in!

**Comment by ckluis** [comment]
thanks!

**Comment by MichaelSL** [comment]
hi @dannyvankooten ! I can't find this enhancement on https://trello.com/b/x2aBwH2J/fathom-roadmap board. Was it rejected?
