### ISSUE TITLE
enhancement: filter query string

### ISSUE THREAD

**Issue by ambernardino** [usefathom/fathom#85]
Hello,
I really like this project, thanks for all the effort you are putting on this! 

Currently we have:
http://abc.com/ - 1 view
http://abc.com/?a=1 - 1 view
http://abc.com/?b=2 - 1 view

Is there the option the filter the query string so that:
http://abc.com/ - 3 views

**Comment by dannyvankooten** [comment]
Hi @ambernardino,

Adding a meta-canonical tag to your page should do that for new pageviews, though not retroactively.

‘<meta rel=“canonical” href=“http://abc.com/“>’

Does that help or would a canonical URL not be the right solution here (eg if you need the different pages indexed on their own).

**Comment by ambernardino** [comment]
Hi @dannyvankooten 

Thanks for the answer, it works on pages that render on the client side but not on the ones that render on the server side. 

Would it be possible to pass a flag to fathom so that it filters the query string?

**Comment by dannyvankooten** [comment]
Hi @ambernardino,

Sorry for being a little slow to respond - we're busy coding up the hosted Fathom offering so that this can be a sustainable effort for everyone involved.

The canonical tag mentioned in my previous comment should really work for both client-side as sever-side rendered pages. Before the Fathom tracking snippet sends the tracking request to `/collect`, it looks for the canonical element on the page and uses that if found.

The only thing that this does not work on is your historical data, but you should be able to fix that by going into your `daily_page_stats` table and running an `UPDATE` query in SQL. We'll try to make that more straightforward in the future!

Does that help? I'm going ahead and will close this issue to keep the issue list clean with actual issues instead of stuff to put on the roadmap, but please don't think that means we won't ever think about making this easier. We will. :-) 

Cheers!
