### ISSUE TITLE
Datepicker doesn't include end date when picking manually

### ISSUE THREAD

**Issue by dannyvankooten** [usefathom/fathom#88]
As [reported on Hacker News](https://news.ycombinator.com/item?id=17500649) (and confirmed).

**Comment by thmsdnnr** [comment]
Perhaps related to passing date as a string instead of a date object in `dateValue()` [DatePicker.js L122](https://github.com/usefathom/fathom/blob/master/assets/src/js/components/DatePicker.js#L122)?

I read about this [known issue (764)](https://github.com/dbushell/Pikaday/issues/764#issuecomment-360286792) w/Pikaday due to `new Date(Date.parse(<DATESTRING>));` https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L799 that can cause off-by-one days.

I noticed clicking predefined intervals ("Today", "This Week", "This Month") shows correct dates on the right and in the graph, but clicking the dates themselves in these cases still has both the Start Date and End Date calendars showing 1 day prior.

Choosing a custom start date shows the correct graph data, but is also one day behind in the calendar view, though there's no functional impact on the data display like there is with end date.
